import { z } from 'zod';

export const EmployeeSchema = z.object({
  id: z.number().optional(),
  empCode: z.string().min(1, "Employee Code is required"),
  biometricId: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  firstName: z.string().optional().nullable(),
  middleName: z.string().optional().nullable(),
  lastName: z.string().optional().nullable(),
  fullNameAadhar: z.string().optional().nullable(),
  fatherHusbandGuardianName: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  dob: z.string().optional().nullable(),
  maritalStatus: z.string().optional().nullable(),
  religion: z.string().optional().nullable(),
  bloodGroup: z.string().optional().nullable(),
  qualification: z.string().optional().nullable(),
  isDifferentlyAbled: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
  disabilityType: z.union([z.string(), z.array(z.string())]).optional().nullable().transform(val => {
    if (!val) return [];
    if (typeof val === 'string') return val.split(',').map(v => v.trim()).filter(Boolean);
    return val;
  }),
  referencedBy: z.string().optional().nullable(),
  mobile: z.string().optional().nullable(),
  mobile2: z.string().optional().nullable(),
  email: z.string().email("Invalid email format").optional().nullable().or(z.literal('')),
  cugMobile: z.string().optional().nullable(),
  currentAddress: z.string().optional().nullable(),
  currentPincode: z.string().optional().nullable(),
  currentPostOffice: z.string().optional().nullable(),
  currentDistrict: z.string().optional().nullable(),
  currentState: z.string().optional().nullable(),
  permAddress: z.string().optional().nullable(),
  permPincode: z.string().optional().nullable(),
  permPostOffice: z.string().optional().nullable(),
  permDistrict: z.string().optional().nullable(),
  permState: z.string().optional().nullable(),
  isPermSameAsCurrent: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
  photoUrl: z.string().optional().nullable(),
  photoPath: z.string().optional().nullable(),
  signatureUrl: z.string().optional().nullable(),
  wageType: z.string().optional().nullable(),
  wageAmount: z.coerce.number().optional().nullable(),
  status: z.union([z.coerce.number(), z.boolean()]).optional().nullable().transform(val => typeof val === 'boolean' ? (val ? 1 : 0) : val),
  blacklistStatus: z.union([z.coerce.number(), z.boolean()]).optional().nullable().transform(val => typeof val === 'boolean' ? (val ? 1 : 0) : val),
  blacklistRemarks: z.string().optional().nullable(),
  blacklistEffectiveDate: z.string().optional().nullable(),
  blacklistAuthorizerId: z.coerce.number().optional().nullable(),
  blacklistAuthorizerName: z.string().optional().nullable(),
  slabId: z.coerce.number().optional().nullable(),
  departmentId: z.coerce.number().optional().nullable(),
  locationId: z.coerce.number().optional().nullable(),
  categoryId: z.coerce.number().optional().nullable(),
  divisionId: z.coerce.number().optional().nullable(),
  groupId: z.coerce.number().optional().nullable(),
  classId: z.coerce.number().optional().nullable(),
  designation: z.string().optional().nullable(),
  designationId: z.coerce.number().optional().nullable(),
  grade: z.string().optional().nullable(),
  gradeId: z.coerce.number().optional().nullable(),
  joiningDate: z.string().optional().nullable(),
  employmentType: z.string().optional().nullable(),
  employmentTypeId: z.coerce.number().optional().nullable(),
  shiftId: z.coerce.number().optional().nullable(),
  aadharNo: z.string().optional().nullable(),
  panNo: z.string().optional().nullable(),
  passportNo: z.string().optional().nullable(),
  uanNo: z.string().optional().nullable(),
  workingDayTypeId: z.string().optional().nullable(),
  basicSalary: z.coerce.number().optional().nullable(),
  hra: z.coerce.number().optional().nullable(),
  conveyance: z.coerce.number().optional().nullable(),
  specialAllowance: z.coerce.number().optional().nullable(),
  bankName: z.string().optional().nullable(),
  accountNo: z.string().optional().nullable(),
  ifscCode: z.string().optional().nullable(),
  drivingLicence: z.string().optional().nullable(),
  voterId: z.string().optional().nullable(),
  esiIpNumber: z.string().optional().nullable(),
  esiJoiningDate: z.string().optional().nullable(),
  pfNumber: z.string().optional().nullable(),
  pfJoiningDate: z.string().optional().nullable(),
  pfExitDate: z.string().optional().nullable(),
  pfExitReason: z.string().optional().nullable(),
  voluntaryPfApplicable: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
  voluntaryPfType: z.string().optional().nullable(),
  voluntaryPfValue: z.coerce.number().optional().nullable(),
  paymentMode: z.string().optional().nullable(),
  asPerBankName: z.string().optional().nullable(),
  bankEffectiveDate: z.string().optional().nullable(),
  employeeStatus: z.string().optional().nullable(),
  employeeStatusId: z.coerce.number().optional().nullable(),
  bookJoiningDate: z.string().optional().nullable(),
  leavingDate: z.string().optional().nullable(),
  reportingEmployeeId: z.coerce.number().optional().nullable(),
  wageEffectiveFrom: z.string().optional().nullable(),
  weeklyOff: z.string().optional().nullable(),
  weeklyOffEffectiveDate: z.string().optional().nullable(),
  parentEmployeeId: z.coerce.number().optional().nullable(),
  salaryProcessSequence: z.coerce.number().optional().nullable(),
  statutoryRate: z.coerce.number().optional().nullable(),
  statutoryWageType: z.string().optional().nullable(),
  statutoryWageAmount: z.coerce.number().optional().nullable(),
});

export const SalaryHeadSchema = z.object({
  id: z.number().optional(),
  name: z.string().min(1, "Name is required"),
  type: z.string().optional().nullable(),
  isDeduction: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
  systemHead: z.string().optional().nullable(),
  baseOn: z.string().optional().nullable(),
  isPartOfCtc: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
  status: z.union([z.coerce.number(), z.boolean()]).optional().nullable().transform(val => typeof val === 'boolean' ? (val ? 1 : 0) : val),
  applicability: z.string().optional().nullable(),
  allocationType: z.string().optional().nullable(),
});

export const TransactionSchema = z.object({
  id: z.number().optional(),
  transactionType: z.enum(['EARNING', 'DEDUCTION']),
  date: z.string().optional(),
  salaryMonthYear: z.string().regex(/^\d{2}-\d{4}$/, "Format must be MM-YYYY"),
  empId: z.number(),
  headId: z.number(),
  amount: z.number().positive("Amount must be positive"),
  reason: z.string().optional().nullable(),
  authorisedBy: z.number().optional().nullable(),
  remark: z.string().optional().nullable(),
  isBulkEntry: z.union([z.coerce.number(), z.boolean()]).optional().transform(val => typeof val === 'number' ? val === 1 : val),
});
