import { 
  DbEmployee, Employee, 
  DbSalaryHead, SalaryHead,
  DbAttendanceLog, AttendanceLog,
  DbPayrollRecord, PayrollRecord
} from '../types/index.js';

export const Mapper = {
  // --- Employee Mapper ---
  employee: {
    toDomain(db: DbEmployee): Employee {
      return {
        id: db.id,
        empCode: db.emp_code,
        biometricId: db.biometric_id,
        name: db.name,
        firstName: db.first_name,
        middleName: db.middle_name,
        lastName: db.last_name,
        fullNameAadhar: db.full_name_aadhar,
        fatherHusbandGuardianName: db.father_husband_guardian_name,
        gender: db.gender,
        dob: db.dob,
        maritalStatus: db.marital_status,
        religion: db.religion,
        bloodGroup: db.blood_group,
        qualification: db.qualification,
        isDifferentlyAbled: !!db.is_differently_abled,
        disabilityType: db.disability_type ? db.disability_type.split(',') : [],
        referencedBy: db.referenced_by,
        mobile: db.mobile,
        mobile2: db.mobile2,
        email: db.email,
        cugMobile: db.cug_mobile,
        currentAddress: db.current_address,
        currentPincode: db.current_pincode,
        currentPostOffice: db.current_post_office,
        currentDistrict: db.current_district,
        currentState: db.current_state,
        permAddress: db.perm_address,
        permPincode: db.perm_pincode,
        permPostOffice: db.perm_post_office,
        permDistrict: db.perm_district,
        permState: db.perm_state,
        isPermSameAsCurrent: !!db.is_perm_same_as_current,
        photoUrl: db.photo_url,
        photoPath: db.photo_path,
        signatureUrl: db.signature_url,
        wageType: db.wage_type,
        wageAmount: db.wage_amount,
        status: db.status,
        isPfCovered: db.is_pf_covered,
        isEsiCovered: db.is_esi_covered,
        blacklistStatus: db.blacklist_status,
        blacklistRemarks: db.blacklist_remarks,
        blacklistEffectiveDate: db.blacklist_effective_date,
        blacklistAuthorizerId: db.blacklist_authorizer_id,
        blacklistAuthorizerName: db.blacklist_authorizer_name,
        slabId: db.slab_id,
        departmentId: db.department_id,
        locationId: db.location_id,
        categoryId: db.category_id,
        divisionId: db.division_id,
        groupId: db.group_id,
        classId: db.class_id,
        designation: db.designation,
        designationId: db.designation_id,
        grade: db.grade,
        gradeId: db.grade_id,
        joiningDate: db.joining_date,
        employmentType: db.employment_type,
        employmentTypeId: db.employment_type_id,
        shiftId: db.shift_id,
        aadharNo: db.aadhar_no,
        panNo: db.pan_no,
        passportNo: db.passport_no,
        uanNo: db.uan_no,
        workingDayTypeId: db.working_day_type_id,
        basicSalary: db.basic_salary,
        hra: db.hra,
        conveyance: db.conveyance,
        specialAllowance: db.special_allowance,
        bankName: db.bank_name,
        accountNo: db.account_no,
        ifscCode: db.ifsc_code,
        drivingLicence: db.driving_licence,
        voterId: db.voter_id,
        esiIpNumber: db.esi_ip_number,
        esiJoiningDate: db.esi_joining_date,
        pfNumber: db.pf_number,
        pfJoiningDate: db.pf_joining_date,
        pfExitDate: db.pf_exit_date,
        pfExitReason: db.pf_exit_reason,
        pfHistory: db.pf_history,
        esiHistory: db.esi_history,
        voluntaryPfApplicable: !!db.voluntary_pf_applicable,
        voluntaryPfType: db.voluntary_pf_type,
        voluntaryPfValue: db.voluntary_pf_value,
        paymentMode: db.payment_mode,
        asPerBankName: db.as_per_bank_name,
        bankEffectiveDate: db.bank_effective_date,
        bankHistory: db.bank_history,
        employeeStatus: db.employee_status,
        employeeStatusId: db.employee_status_id,
        bookJoiningDate: db.book_joining_date,
        leavingDate: db.leaving_date,
        reportingEmployeeId: db.reporting_employee_id,
        wageEffectiveFrom: db.wage_effective_from,
        weeklyOff: db.weekly_off,
        weeklyOffEffectiveDate: db.weekly_off_effective_date,
        parentEmployeeId: db.parent_employee_id,
        salaryProcessSequence: db.salary_process_sequence,
        statutoryRate: db.statutory_rate,
        statutoryWageType: db.statutory_wage_type,
        statutoryWageAmount: db.statutory_wage_amount,
        createdAt: db.created_at
      };
    },
    toPersistence(domain: Employee): DbEmployee {
      return {
        id: domain.id,
        emp_code: domain.empCode,
        biometric_id: domain.biometricId,
        name: domain.name,
        first_name: domain.firstName,
        middle_name: domain.middleName,
        last_name: domain.lastName,
        full_name_aadhar: domain.fullNameAadhar,
        father_husband_guardian_name: domain.fatherHusbandGuardianName,
        gender: domain.gender,
        dob: domain.dob,
        marital_status: domain.maritalStatus,
        religion: domain.religion,
        blood_group: domain.bloodGroup,
        qualification: domain.qualification,
        is_differently_abled: domain.isDifferentlyAbled ? 1 : 0,
        disability_type: Array.isArray(domain.disabilityType) ? domain.disabilityType.join(',') : domain.disabilityType,
        referenced_by: domain.referencedBy,
        mobile: domain.mobile,
        mobile2: domain.mobile2,
        email: domain.email,
        cug_mobile: domain.cugMobile,
        current_address: domain.currentAddress,
        current_pincode: domain.currentPincode,
        current_post_office: domain.currentPostOffice,
        current_district: domain.currentDistrict,
        current_state: domain.currentState,
        perm_address: domain.permAddress,
        perm_pincode: domain.permPincode,
        perm_post_office: domain.permPostOffice,
        perm_district: domain.permDistrict,
        perm_state: domain.permState,
        is_perm_same_as_current: domain.isPermSameAsCurrent ? 1 : 0,
        photo_url: domain.photoUrl,
        photo_path: domain.photoPath,
        signature_url: domain.signatureUrl,
        wage_type: domain.wageType,
        wage_amount: domain.wageAmount,
        status: domain.status,
        is_pf_covered: domain.isPfCovered,
        is_esi_covered: domain.isEsiCovered,
        blacklist_status: domain.blacklistStatus,
        blacklist_remarks: domain.blacklistRemarks,
        blacklist_effective_date: domain.blacklistEffectiveDate,
        blacklist_authorizer_id: domain.blacklistAuthorizerId,
        blacklist_authorizer_name: domain.blacklistAuthorizerName,
        slab_id: domain.slabId,
        department_id: domain.departmentId,
        location_id: domain.locationId,
        category_id: domain.categoryId,
        division_id: domain.divisionId,
        group_id: domain.groupId,
        class_id: domain.classId,
        designation: domain.designation,
        designation_id: domain.designationId,
        grade: domain.grade,
        grade_id: domain.gradeId,
        joining_date: domain.joiningDate,
        employment_type: domain.employmentType,
        employment_type_id: domain.employmentTypeId,
        shift_id: domain.shiftId,
        aadhar_no: domain.aadharNo,
        pan_no: domain.panNo,
        passport_no: domain.passportNo,
        uan_no: domain.uanNo,
        working_day_type_id: domain.workingDayTypeId,
        basic_salary: domain.basicSalary,
        hra: domain.hra,
        conveyance: domain.conveyance,
        special_allowance: domain.specialAllowance,
        bank_name: domain.bankName,
        account_no: domain.accountNo,
        ifsc_code: domain.ifscCode,
        driving_licence: domain.drivingLicence,
        voter_id: domain.voterId,
        esi_ip_number: domain.esiIpNumber,
        esi_joining_date: domain.esiJoiningDate,
        pf_number: domain.pfNumber,
        pf_joining_date: domain.pfJoiningDate,
        pf_exit_date: domain.pfExitDate,
        pf_exit_reason: domain.pfExitReason,
        pf_history: domain.pfHistory,
        esi_history: domain.esiHistory,
        voluntary_pf_applicable: domain.voluntaryPfApplicable ? 1 : 0,
        voluntary_pf_type: domain.voluntaryPfType,
        voluntary_pf_value: domain.voluntaryPfValue,
        payment_mode: domain.paymentMode,
        as_per_bank_name: domain.asPerBankName,
        bank_effective_date: domain.bankEffectiveDate,
        bank_history: domain.bankHistory,
        employee_status: domain.employeeStatus,
        employee_status_id: domain.employeeStatusId,
        book_joining_date: domain.bookJoiningDate,
        leaving_date: domain.leavingDate,
        reporting_employee_id: domain.reportingEmployeeId,
        wage_effective_from: domain.wageEffectiveFrom,
        weekly_off: domain.weeklyOff,
        weekly_off_effective_date: domain.weeklyOffEffectiveDate,
        parent_employee_id: domain.parentEmployeeId,
        salary_process_sequence: domain.salaryProcessSequence,
        statutory_rate: domain.statutoryRate,
        statutory_wage_type: domain.statutoryWageType,
        statutory_wage_amount: domain.statutoryWageAmount,
        created_at: domain.createdAt
      };
    }
  },

  // --- SalaryHead Mapper ---
  salaryHead: {
    toDomain(db: DbSalaryHead): SalaryHead {
      return {
        id: db.id,
        name: db.name,
        type: db.type,
        isDeduction: !!db.is_deduction,
        systemHead: db.system_head,
        baseOn: db.base_on,
        isPartOfCtc: !!db.is_part_of_ctc,
        status: db.status,
        createdAt: db.created_at,
        applicability: db.applicability,
        allocationType: db.allocation_type
      };
    },
    toPersistence(domain: SalaryHead): DbSalaryHead {
      return {
        id: domain.id,
        name: domain.name,
        type: domain.type,
        is_deduction: domain.isDeduction ? 1 : 0,
        system_head: domain.systemHead,
        base_on: domain.baseOn,
        is_part_of_ctc: domain.isPartOfCtc ? 1 : 0,
        status: domain.status,
        created_at: domain.createdAt,
        applicability: domain.applicability,
        allocation_type: domain.allocationType
      };
    }
  },

  // --- AttendanceLog Mapper ---
  attendanceLog: {
    toDomain(db: DbAttendanceLog): AttendanceLog {
      return {
        id: db.id,
        empId: db.emp_id,
        empCode: db.emp_code,
        empName: db.emp_name,
        departmentName: db.department_name,
        designationName: db.designation_name,
        shiftName: db.shift_name,
        shiftId: db.shift_id,
        machineName: db.machine_name,
        date: db.date,
        punchIn: db.punch_in,
        punchOut: db.punch_out,
        totalTimeMins: db.total_time_mins,
        workedMins: db.worked_mins,
        outsideMins: db.outside_mins,
        attendanceValue: db.attendance_value,
        status: db.status,
        isMissedPunch: !!db.is_missed_punch,
        blacklistStatus: db.blacklist_status,
        punches: db.punches
      };
    },
    toPersistence(domain: AttendanceLog): DbAttendanceLog {
      return {
        id: domain.id,
        emp_id: domain.empId,
        emp_code: domain.empCode,
        emp_name: domain.empName,
        department_name: domain.departmentName,
        designation_name: domain.designationName,
        shift_name: domain.shiftName,
        shift_id: domain.shiftId,
        machine_name: domain.machineName,
        date: domain.date,
        punch_in: domain.punchIn,
        punch_out: domain.punchOut,
        total_time_mins: domain.totalTimeMins,
        worked_mins: domain.workedMins,
        outside_mins: domain.outsideMins,
        attendance_value: domain.attendanceValue,
        status: domain.status,
        is_missed_punch: domain.isMissedPunch ? 1 : 0,
        blacklist_status: domain.blacklistStatus,
        punches: domain.punches
      };
    }
  },

  // --- PayrollRecord Mapper ---
  payrollRecord: {
    toDomain(db: DbPayrollRecord): PayrollRecord {
      return {
        id: db.id,
        empId: db.emp_id,
        month: db.month,
        typeName: db.type_name,
        actualAttendance: db.actual_attendance,
        statutoryAttendance: db.statutory_attendance,
        actualEarning: db.actual_earning,
        pf: db.pf,
        esi: db.esi,
        loanEmi: db.loan_emi,
        canteenDeduction: db.canteen_deduction,
        netPayable: db.net_payable,
        statutoryGross: db.statutory_gross,
        adjustedDiff: db.adjusted_diff,
        status: db.status,
        approvedBy: db.approved_by,
        lockedAt: db.locked_at,
        createdAt: db.created_at,
        updatedAt: db.updated_at
      };
    },
    toPersistence(domain: PayrollRecord): DbPayrollRecord {
      return {
        id: domain.id,
        emp_id: domain.empId,
        month: domain.month,
        type_name: domain.typeName,
        actual_attendance: domain.actualAttendance,
        statutory_attendance: domain.statutoryAttendance,
        actual_earning: domain.actualEarning,
        pf: domain.pf,
        esi: domain.esi,
        loan_emi: domain.loanEmi,
        canteen_deduction: domain.canteenDeduction,
        net_payable: domain.netPayable,
        statutory_gross: domain.statutoryGross,
        adjusted_diff: domain.adjustedDiff,
        status: domain.status,
        approved_by: domain.approvedBy,
        locked_at: domain.lockedAt,
        created_at: domain.createdAt,
        updated_at: domain.updatedAt
      };
    }
  }
};
